name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install --upgrade scrapy twisted pyopenssl pandas wordcloud matplotlib nltk textblob pysentimiento

    - name: Extract information
      run: scrapy crawl discursospider

    - name: NLP
      run: python3 analisis_sentimientos.py 

    - name: Generate images
      run: |
        python3 nube_de_palabras.py
        python3 graficos_sentimientos.py

    - name: Install npm & build website
      run: |
        cd app
        npm install
        npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./app/build
