name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install scrapy
      run: |
        pip install scrapy

    - name: Extract information
      run: scrapy crawl discursospider

    - name: Generate images
      run: python3 nube_de_palabras.py

    - name: Install npm & build website
      run: |
        cd app
        npm install
        npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build